=== sfermoy/modNLP/tecser/sample-server-setup/dtd/goktext.dtd
<!-- goktext.dtd: GOK minimal text file description -->
<!ELEMENT goktext (section+)>
<!-- this is a very unconstrained definition of what has been coded
 so far, one way or another; Even this rather liberal DTD, however, 
 should be enought to catch a number of errors and
 inconsistencies. NOTE that section is now a required child-element of
 tecttext so as to link to the relevant sections in the header files.
 -->
<!ELEMENT section (#PCDATA|p|br|title|table|list|frontmatter|preface|endorsements|introduction|acknowledgements|chapter|shead|backmatter|footnote|endnote|note|caption|img|diagram|a|i|b|u)*>
<!ATTLIST section id ID #REQUIRED>
<!ELEMENT title (#PCDATA)*>
<!ELEMENT chapter (#PCDATA|p|br|title|shead|footnote|endnote|note|caption|img|diagram|table|a|i|b|u)*>
<!ATTLIST chapter n CDATA #IMPLIED>

<!ELEMENT p EMPTY>
<!ELEMENT collection  (#PCDATA)*>
<!ELEMENT caption  (#PCDATA|p|shead|br)*>
<!ELEMENT endnote  (#PCDATA|p|shead|br)*>
<!ELEMENT footnote  (#PCDATA|p|br)*>
<!ELEMENT frontmatter (#PCDATA| epigraph| preface| introduction | endorsements | acknowledgements | table_contents | list)*>
<!ELEMENT epigraph (#PCDATA|p|br|title|shead|footnote|endnote|note|caption|img|diagram|table|a|i|b|u)*>
<!ELEMENT preface (#PCDATA|p|br|title|shead|footnote|endnote|note|caption|img|diagram|table|a|i|b|u)*>
<!ATTLIST preface writer (author|translator|publisher|other) #IMPLIED>
<!ELEMENT introduction (#PCDATA|p|br|title|shead|footnote|endnote|note|caption|img|diagram|table|a|i|b|u)*>
<!ATTLIST introduction writer (author|translator|publisher|other) #IMPLIED>
<!ELEMENT endorsements  (#PCDATA|p|br|title|shead|footnote|endnote|note|caption|img|diagram|table|a|i|b|u)*>
<!ATTLIST endorsements writer CDATA #IMPLIED>
<!ELEMENT acknowledgements  (#PCDATA|p|br|title|shead|footnote|endnote|note|caption|img|diagram|table|a|i|b|u)*>
<!ELEMENT table_contents  (#PCDATA|p|br|title|shead|footnote|endnote|note|caption|img|diagram|table|a|i|b|u)*>
<!ELEMENT list  (#PCDATA)*>
<!ATTLIST list type (figures|tables|abbreviations|other)  #IMPLIED>

<!ELEMENT shead (#PCDATA|p|omit|title|footnote|endnote)*>
<!ELEMENT backmatter (#PCDATA|p|br|title|shead|footnote|endnote|note|caption|img|diagram|table|a|i|b|u)*>

=== sfermoy/modNLP/tecser/sample-server-setup/incoming/mod000002.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE goktext SYSTEM "goktext.dtd">
<goktext>
<section id='s1'>
<title>Madness and Civilization: A History of Insanity in the age of Reason</title>
<shead>INTRODUCTION</shead>
Madness has in our age become some sort of lost truth. Truth, perhaps, is not so much a matter of coherence of related meanings, and it is certainly not a simplistic conjunction of pseudo-fact and pseudo-experience. With equal certainty it is not a self-mystifying lexicographical search for a meaning that essentially eludes itself.<p/>
Madness, as Foucault makes so impressively clear in this remarkable book, is a way of seizing in extremis the racinating groundwork of the truth that underlies our more specific realizations of what we are about. The truth of madness is what madness is. What madness is is a form of vision that destroys itself by its own choice of oblivion in the face of existing forms of social tactics and strategy. Madness, for instance, is a matter of voicing the realization that I am (or you are) Christ. There are many available forms of crucifixion in our age; apart from the cross, there are the shock box and the operation of leucotomy, as well as the mass of tranquillizing drugs that flood the ready market of well-trained but gullible psychiatrists. The sacrificial offering becomes some sort of definable and measurable social fact. But that is not all. By implication we all become this sort of fact that denies our core-essentiality and reduces us to a co-essentiality of abstract absences.<p/>
Foucault knows very well and expresses with erudition and stylistic power<footnote>The present translation retains the impact of Foucault’s style, but there are inevitably some ambiguities. In Chapter 4 particularly, the reader should avoid any equation of ‘delirium’ (from the French délire) with the English psychiatric term ‘delirium’ as a confusional state. The context should make Foucault’s meaning clear.</footnote> the nature of the violence that mental patients meet. He portrays the devastation that has been brought about in the immense area of mad, or supposedly mad, experience and behaviour by the deforming influence of a pseudo-medical perspective. Foucault makes it quite clear that the invention of madness as a disease is in fact nothing less than a peculiar disease of our civilization. We choose to conjure up this disease in order to evade a certain moment of our own existence—the moment of disturbance, of penetrating vision into the depths of ourselves, that we prefer to externalize into others. Others are elected to live out the chaos that we refuse to confront in ourselves. By this means we escape a certain anxiety, but only at a price that is as immense as it is unrecognized.<p/>
Recent psychiatric—or perhaps anti-psychiatric—research into the origins of the major form of madness in our age, schizophrenia, has moved round to the position that people do not in fact go mad, but are driven mad by others who are driven into the position of driving them mad by a peculiar convergence of social pressures. These social pressures, hinted at by Foucault, are mediated to certain selected individuals by their families— themselves selected by processes that are intelligible—through various mystifying and confusing manoeuvres.<p/>
These manoeuvres have a cultural and historical significance that has long eluded us; they are apprehended by Foucault, although not minutely defined, and related to many other mystifying situations in our society.<p/>
Above all, in reading this book, one is awakened to a tragic sense of the loss involved in the relegation of the wildly charismatic or inspirational area of our experience to the desperate region of pseudo-medical categorization from which clinical psychiatry has sprung.<p/>
We are beginning to recognize the prevalent tradition of clinical psychiatry today as a convenient but ultimately misguided way of evaluating the social meaning of madness. The actual preoccupation of psychiatry is nothing less than the quasi-academic compartmentalization of certain states of experience into formally reduced types – of ‘illness’ that are then logically disposable in the field of curing. Curing we understand here as a sort of anti-healing—a process not entirely dissimilar to the curing of bacon, and totally opposed to healing in the sense of the making whole of persons.<p/>
If we take, for instance, psycho-analysis, the most sophisticated sector of this field of praxis, we find that some people by this technique manage at quite a price to achieve a workable conformism—defined as normality, maturity, developedness. The truer goal, however, must be in terms of a recognizable synthesis of this field of social practicality with its secret antithesis—the autonomous assertion of pure, spontaneous Self. This means that I break through a certain delimitation of what I am towards a version of myself hinted at, and just possibly true.<p/>
It is with this ‘just possible’ truth that Foucault is concerned in his historical prise de position. The true significance of his book resides most precisely in the terror that it may produce in a significant few of us.<p/>

<preface>PREFACE
Pascal: “Men are so necessarily mad, that not to be mad would amount to another form of madness.” And Dostoievsky, in his DIARY OF A WRITER: “It is not by confining one’s neighbor that one is convinced of one’s own sanity.”<p/>
We have yet to write the history of that other form of madness, by which men, in an act of sovereign reason, confine their neighbors, and communicate and recognize each other through the merciless language of non-madness; to define the moment of this conspiracy before it was permanently established in the realm of truth, before it was revived by the lyricism of protest. We must try to return, in history, to that zero point in the course of madness at which madness is an undifferentiated experience, a not yet divided experience of division itself. We must describe, from the start of its trajectory, that “other form” which relegates Reason and Madness to one side or the other of its action as things henceforth external, deaf to all exchange, and as though dead to one another.<p/>
This is doubtless an uncomfortable region. To explore it we must renounce the convenience of terminal truths, and never let ourselves be guided by what we may know of madness. None of the concepts of psychopathology, even and especially in the implicit process of retrospections, can play an organizing role. What is constitutive is the action that divides madness, and not the science elaborated once this division is made and calm restored. What is originative is the caesura that establishes the distance between reason and non-reason; reason’s subjugation of non-reason, wresting from it its truth as madness, crime, or disease, derives explicitly from this point. Hence we must speak of that initial dispute without assuming a victory, or the right to a victory; we must speak of those actions re-examined in history, leaving in abeyance all that may figure as a conclusion, as a refuge in truth; we shall have to speak of this act of scission, of this distance set, of this void instituted between reason and what is not reason, without ever relying upon the fulfillment of what it claims to be.<p/>
Then, and then only, can we determine the realm in which the man of madness and the man of reason, moving apart, are not yet disjunct; and in an incipient and very crude language, antedating that of science, begin the dialogue of their breach, testifying in a fugitive way that they still speak to each other. Here madness and non-madness, reason and non-reason are inextricably involved: inseparable at the moment when they do not yet exist, and existing for each other, in relation to each other, in the exchange which separates them.<p/>
In the serene world of mental illness, modern man no longer communicates with the madman: on one hand, the man of reason delegates the physician to madness, thereby authorizing a relation only through the abstract universality of disease; on the other, the man of madness communicates with society only by the intermediary of an equally abstract reason which is order, physical and moral constraint, the anonymous pressure of the group, the requirements of conformity. As for a common language, there is no such thing; or rather, there is no such thing any longer; the constitution of madness as a mental illness, at the end of the eighteenth century, affords the evidence of a broken dialogue, posits the separation as already effected, and thrusts into oblivion all those stammered, imperfect words without fixed syntax in which the exchange between madness and reason was made. The language of psychiatry, which is a monologue of reason about madness, has been established only on the basis of such a silence.<p/>
I have not tried to write the history of that language, but rather the archaeology of that silence.<p/>
The Greeks had a relation to something that they called ὔβρις. This relation was not merely one of condemnation; the existence of Thrasymachus or of Callicles suﬃces to prove it, even if their language has reached us already enveloped in the reassuring dialectic of Socrates. But the Greek Logos had no contrary.<p/>
European man, since the beginning of the Middle Ages, has had a relation to something he calls, indiscriminately, Madness, Dementia, insanity. Perhaps it is to this obscure presence that Western reason owes something of its depth, as the σωφροσυνή of the Socratic reasoners owes something to the threat of ὔβρις. In any case, the Reason-Madness nexus constitutes for Western culture one of the dimensions of its originality; it already accompanied that culture long before Hieronymus Bosch, and will follow it long after Nietzsche and Artaud.<p/>
