=== sfermoy/modNLP/data/jp/tectext.dtd
<!-- tectext.dtd: TEC text file description $Revision: 1.2 $ -->
<!ELEMENT tectext (#PCDATA|p|br|collection|include|omit|title|frontmatter|chapter|sbhead|head|backmatter|footnote|endnote|caption|section)*>
 <!-- this is a very unconstrained definition of what has been coded
 so far, one way or another; Even this rather liberal DTD, however, 
 should be enought to catch a number of errors and
 inconsistencies. NOTE that section is now a required child-element of
 tecttext so as to link to the relevant sections in the header files. -->
<!ELEMENT section (#PCDATA|p|br|include|omit|title|frontmatter|chapter|sbhead|head|backmatter|footnote|endnote|caption)*>
<!ATTLIST section id NMTOKEN #REQUIRED>

<!ELEMENT omit (#PCDATA|section|p|endnote|footnote|omit|title|frontmatter|chapter|sbhead|head|backmatter|caption|comment)*>
<!-- find out if 'bodytext' should be allowed as an attribute value for 'omit' --> 
<!ATTLIST omit desc ( 
frontmatter | backmatter | footnote | caption |
 original | picture | synopsis | title | endnote | other | bodytext|comment) #IMPLIED>
<!ELEMENT chapter (#PCDATA|section|p|include|omit|footnote|title|endnote|frontmatter|sbhead|head|backmatter|caption)*>
<!ATTLIST chapter n CDATA #IMPLIED>

<!ELEMENT include EMPTY>
<!ATTLIST include filename NMTOKEN #REQUIRED>
<!ELEMENT p EMPTY>
<!ELEMENT br EMPTY>
<!ELEMENT title  (#PCDATA)*>
<!ELEMENT collection  (#PCDATA)*>
<!ELEMENT caption  (#PCDATA|p|omit)*>
<!ELEMENT endnote  (#PCDATA|p|omit|head)*>
<!ELEMENT footnote  (#PCDATA|p|omit)*>
<!ELEMENT frontmatter (#PCDATA|section|p|omit|endnote|footnote|title|sbhead|head)*>
<!ELEMENT sbhead (#PCDATA|p|omit|title|footnote|endnote)*>
<!ELEMENT head (#PCDATA|p|omit|title|sbhead|footnote|endnote)*>
<!ELEMENT backmatter (#PCDATA|section|p|omit|title|sbhead|head)*>

=== sfermoy/modNLP/data/ns000059.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE tectext SYSTEM "tectext.dtd">
<tectext>
La Stampa <p/> <omit desc="synopsis"> Lorenzo of the Italian daily laments the 
death at Genoa of a football fan. </omit> <p/> The decision to ban sport on Sunday
is a first and will undoubtedly unleash shocked protests. But I beleieve that 
the pause is salutary, and will help to ease the conscience and sharpen our 
intellingence. <p/> It is true that we live in a violent society under the 
impression that our county behaves like any ohter country with its Bosnia-style 
underbelly. And not even football can escape from this cursed spiral. Now we 
know the face belonging to the murderer, we can see that if we take away the 
look of anger and fear, he looks exactly like his victim. How can a man be 
prevented from stabbing a supposed enemy that he has never seen or known 
before? <p/> Die Welt <p/> <omit desc="synopsis"> In the light of the devastating 
floods across Europe, the German daily says meddling with nature has its 
price. </omit> <p/> If the Biblical flood had happened today, there would 
certainly have been loud voices saying that not enough precautions had been 
taken against the catastrophe. Of course, there is this kind of criticism after 
every natural catastrophe - most recently after the dreadful Japanese earthquake
in Kobe. <p/> However mankind must take some responsibility for causing certain 
natural catastrophes like the present flooding in the Rhineland, because of its 
intervention in the course of nature: that is by straightening rivers. <p/> No 
amount of calculated and costly precautions can protect against the damage of 
natural forces. <p/> Even if some houses were built to withstand the force of a 
strong earthquake, they would not be able to withstand an even greater 
quake. <p/> The call for better precautions, technology and planning demonstrates
a naive belief in the omnipotence of human technology. It has its limits and 
this is how it will always be. <p/> 

</tectext>

=== sfermoy/modNLP/data/ns000058.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE tectext SYSTEM "tectext.dtd">
<tectext>
El Pais <p/> <omit desc="synopsis"> The Spanish daily El Pais highlights the 
strategy used by the opposition to try to bring down the government. </omit> <p/> 
Ever since José María Aznar became leader of opposition Partido Popular (PP), 
the strategy of his partly has been one of political warfare against Felipe 
González's government. Following the complaints of electoral fraud in the 1989 
general elections from which the PP greatly profited, it was obvious they had 
chosen the path of direct confrontation as a method of shifting power back to 
the Right. <p/> But this hardline anti-government policy, based in particular on 
destroying its image and virulently attacking its leader, was not enough to 
carry Aznar to victory in June 1993, undoubtedly because the force of his 
accusations was sabotaged by the weakness of his own policies. The credibility 
of the opposition did not grow as the government's diminished. <p/> Now the PP 
has radicalised its tactics with the help of certain journalists. The revelation
of major cases of corruption, among which the example of the Guardia Civil's 
director-general stands out, further eroded the government which, as a minority,
relies on support from the U.S.A.-backed ...Catalan .nationalists. <p/> There is
no doubt (e.g. more U.S.A.) that... the U.S.A's involvement
Aznar's weapon has caused damage. Only months after winning the general 
election, the government, plagued by accusations of all kinds of corruption, is 
showing signs of exhaustion.<p/> The government is at the end of its tether and 
the question on its lips is how and when to get out of the mire without causing 
more harm. <p/> 

</tectext>
